<script>
    var options = {
        selector: "#{{ $editorSelector ?? 'kt_docs_tinymce_basic' }}", 
        height:1000,
        menubar: true,
        promotion: false,
        language: 'zh_TW',
        toolbar: [
            "styles fontsize fontsizeinput forecolor backcolor bold italic underline lineheight alignleft aligncenter alignright alignjustify wordcount accordion anchor undo redo link unlink bullist numlist outdent indent blockquote image emoticons fullscreen insertdatetime searchreplace table code"
            /**
             * Supported Tool
             * 
             * cut
             * copy
             * paste
             * 
             * tabledelete
             * tableprops
             * tablerowprops
             * tablecellprops
             * tableinsertrowbefore
             * tableinsertrowafter
             * tabledeleterow
             * tableinsertcolbefore
             * tableinsertcolafter
             * tabledeletecol
             */

        ],
        plugins : "lists advlist code image table wordcount link emoticons fullscreen insertdatetime searchreplace accordion anchor",
        images_file_types: 'jpg,svg,webp,png',
        images_upload_url: '{{ route("uploads.image") }}',
        // images_upload_base_path: '/some/basepath',
        image_class_list: [
            { title: 'img-fluid', value: 'img-fluid' },


        ],
        image_title: true,
        automatic_uploads: true,
        toolbar_sticky: true,
        toolbar_sticky_offset: 0,
        content_style: 'img { max-width: 100%; height: auto; }' ,


    }

    if ( KTThemeMode.getMode() === "dark" ) {
        options["skin"] = "oxide-dark";
        options["content_css"] = "dark";
    }

    tinymce.init(options);

    //繁中
    tinymce.addI18n('zh_TW',{ 
        "Redo": "恢復",
        "Undo": "撤銷",
        "Cut": "剪切",
        "Copy": "復制",
        "Paste": "粘貼",
        "Select all": "全選",
        "New document": "新建文檔",
        "Ok": "確定",
        "Cancel": "取消",
        "Visual aids": "網格線",
        "Bold": "粗體",
        "Italic": "斜體",
        "Underline": "下劃線",
        "Strikethrough": "刪除線",
        "Superscript": "上標",
        "Subscript": "下標",
        "Clear formatting": "清除格式",
        "Align left": "左對齊",
        "Align center": "居中",
        "Align right": "右對齊",
        "Justify": "兩端對齊",
        "Bullet list": "符號列表",
        "Numbered list": "數字列表",
        "Decrease indent": "減少縮進",
        "Increase indent": "增加縮進",
        "Close": "關閉",
        "Formats": "格式",
        "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.": "當前瀏覽器不支持訪問剪貼板，請使用快捷鍵Ctrl+X/C/V復制粘貼",
        "Headers": "標題",
        "Header 1": "標題1",
        "Header 2": "標題2",
        "Header 3": "標題3",
        "Header 4": "標題4",
        "Header 5": "標題5",
        "Header 6": "標題6",
        "Headings": "標題",
        "Heading 1": "標題1",
        "Heading 2": "標題2",
        "Heading 3": "標題3",
        "Heading 4": "標題4",
        "Heading 5": "標題5",
        "Heading 6": "標題6",
        "Preformatted": "預格式化",
        "Div": "Div區塊",
        "Pre": "預格式文本",
        "Code": "代碼",
        "Paragraph": "段落",
        "Blockquote": "引用",
        "Inline": "文本",
        "Blocks": "區塊",
        "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "當前為純文本粘貼模式，再次點擊可以回到普通粘貼模式。",
        "Fonts": "字體",
        "Font Sizes": "字號",
        "Class": "Class",
        "Browse for an image": "瀏覽圖像",
        "OR": "或",
        "Drop an image here": "拖放壹張圖片文件至此",
        "Upload": "上傳",
        "Block": "塊",
        "Align": "對齊",
        "Default": "默認",
        "Circle": "空心圓",
        "Disc": "實心圓",
        "Square": "方塊",
        "Lower Alpha": "小寫英文字母",
        "Lower Greek": "小寫希臘字母",
        "Lower Roman": "小寫羅馬字母",
        "Upper Alpha": "大寫英文字母",
        "Upper Roman": "大寫羅馬字母",
        "Anchor...": "錨點...",
        "Name": "名稱",
        "Id": "id",
        "Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "id應該以字母開頭，後跟字母、數字、橫線、點、冒號或下劃線。",
        "You have unsaved changes are you sure you want to navigate away?": "妳對文檔的修改尚未儲存，確定離開嗎？",
        "Restore last draft": "恢復上次的草稿",
        "Special characters...": "特殊字符...",
        "Source code": "HTML源碼",
        "Insert/Edit code sample": "插入/編輯代碼示例",
        "Language": "語言",
        "Code sample...": "代碼示例...",
        "Color Picker": "選取顏色",
        "R": "R",
        "G": "G",
        "B": "B",
        "Left to right": "從左到右",
        "Right to left": "從右到左",
        "Emoticons...": "表情符號...",
        "Metadata and Document Properties": "元數據和文檔屬性",
        "Title": "標題",
        "Keywords": "關鍵詞",
        "Description": "描述",
        "Robots": "機器人",
        "Author": "作者",
        "Encoding": "編碼",
        "Fullscreen": "全屏",
        "Action": "操作",
        "Shortcut": "快捷鍵",
        "Help": "幫助",
        "Address": "地址",
        "Focus to menubar": "移動焦點到菜單欄",
        "Focus to toolbar": "移動焦點到工具欄",
        "Focus to element path": "移動焦點到元素路徑",
        "Focus to contextual toolbar": "移動焦點到上下文菜單",
        "Insert link (if link plugin activated)": "插入鏈接 (如果鏈接插件已激活)",
        "Save (if save plugin activated)": "儲存(如果儲存插件已激活)",
        "Find (if searchreplace plugin activated)": "查找(如果查找替換插件已激活)",
        "Plugins installed ({0}):": "已安裝插件 ({0})：",
        "Premium plugins:": "優秀插件：",
        "Learn more...": "了解更多...",
        "You are using {0}": "妳正在使用 {0}",
        "Plugins": "插件",
        "Handy Shortcuts": "快捷鍵",
        "Horizontal line": "水平分割線",
        "Insert/edit image": "插入/編輯圖片",
        "Image description": "圖片描述",
        "Source": "地址",
        "Dimensions": "大小",
        "Constrain proportions": "保持寬高比",
        "General": "常規",
        "Advanced": "高級",
        "Style": "樣式",
        "Vertical space": "垂直邊距",
        "Horizontal space": "水平邊距",
        "Border": "邊框",
        "Insert image": "插入圖片",
        "Image...": "圖片...",
        "Image list": "圖片列表",
        "Rotate counterclockwise": "逆時針旋轉",
        "Rotate clockwise": "順時針旋轉",
        "Flip vertically": "垂直翻轉",
        "Flip horizontally": "水平翻轉",
        "Edit image": "編輯圖片",
        "Image options": "圖片選項",
        "Zoom in": "放大",
        "Zoom out": "縮小",
        "Crop": "裁剪",
        "Resize": "調整大小",
        "Orientation": "方向",
        "Brightness": "亮度",
        "Sharpen": "銳化",
        "Contrast": "對比度",
        "Color levels": "色階",
        "Gamma": "伽馬值",
        "Invert": "反轉",
        "Apply": "應用",
        "Back": "後退",
        "Insert date/time": "插入日期/時間",
        "Date/time": "日期/時間",
        "Insert/Edit Link": "插入/編輯鏈接",
        "Insert/edit link": "插入/編輯鏈接",
        "Text to display": "顯示文字",
        "Url": "地址",
        "Open link in...": "鏈接打開方式...",
        "Current window": "當前窗口打開",
        "None": "在當前窗口/框架打開",
        "New window": "在新窗口打開",
        "Remove link": "刪除鏈接",
        "Anchors": "錨點",
        "Link...": "鏈接...",
        "Paste or type a link": "粘貼或輸入鏈接",
        "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "妳所填寫的URL地址為郵件地址，需要加上mailto:前綴嗎？",
        "The URL you entered seems to be an external link. Do you want to add the required http:// prefix?": "妳所填寫的URL地址屬於外部鏈接，需要加上http://:前綴嗎？",
        "Link list": "鏈接列表",
        "Insert video": "插入視頻",
        "Insert/edit video": "插入/編輯視頻",
        "Insert/edit media": "插入/編輯媒體",
        "Alternative source": "替代資源",
        "Alternative image URL": "資源備用地址",
        "Media poster (Image URL)": "封面(圖片地址)",
        "Paste your embed code below:": "將內嵌代碼粘貼在下面:",
        "Embed": "內嵌",
        "Media...": "多媒體...",
        "Nonbreaking space": "不間斷空格",
        "Page break": "分頁符",
        "Paste as text": "粘貼為文本",
        "Preview": "預覽",
        "Print...": "打印...",
        "Save": "儲存",
        "Find": "查找",
        "Replace with": "替換為",
        "Replace": "替換",
        "Replace all": "替換全部",
        "Previous": "上壹個",
        "Next": "下壹個",
        "Find and replace...": "查找並替換...",
        "Could not find the specified string.": "未找到搜索內容。",
        "Match case": "區分大小寫",
        "Find whole words only": "全單詞匹配",
        "Spell check": "拼寫檢查",
        "Ignore": "忽略",
        "Ignore all": "忽略全部",
        "Finish": "完成",
        "Add to Dictionary": "添加到字典",
        "Insert table": "插入表格",
        "Table properties": "表格屬性",
        "Delete table": "刪除表格",
        "Cell": "單元格",
        "Row": "行",
        "Column": "列",
        "Cell properties": "單元格屬性",
        "Merge cells": "合並單元格",
        "Split cell": "拆分單元格",
        "Insert row before": "在上方插入",
        "Insert row after": "在下方插入",
        "Delete row": "刪除行",
        "Row properties": "行屬性",
        "Cut row": "剪切行",
        "Copy row": "復制行",
        "Paste row before": "粘貼到上方",
        "Paste row after": "粘貼到下方",
        "Insert column before": "在左側插入",
        "Insert column after": "在右側插入",
        "Delete column": "刪除列",
        "Cols": "列",
        "Rows": "行",
        "Width": "寬",
        "Height": "高",
        "Cell spacing": "單元格外間距",
        "Cell padding": "單元格內邊距",
        "Show caption": "顯示標題",
        "Left": "左對齊",
        "Center": "居中",
        "Right": "右對齊",
        "Cell type": "單元格類型",
        "Scope": "範圍",
        "Alignment": "對齊方式",
        "H Align": "水平對齊",
        "V Align": "垂直對齊",
        "Top": "頂部對齊",
        "Middle": "垂直居中",
        "Bottom": "底部對齊",
        "Header cell": "表頭單元格",
        "Row group": "行組",
        "Column group": "列組",
        "Row type": "行類型",
        "Header": "表頭",
        "Body": "表體",
        "Footer": "表尾",
        "Border color": "邊框顏色",
        "Insert template...": "插入模板...",
        "Templates": "模板",
        "Template": "模板",
        "Text color": "文字顏色",
        "Background color": "背景色",
        "Custom...": "自定義...",
        "Custom color": "自定義顏色",
        "No color": "無",
        "Remove color": "刪除顏色",
        "Table of Contents": "目錄",
        "Show blocks": "顯示區塊邊框",
        "Show invisible characters": "顯示不可見字符",
        "Word count": "字數統計",
        "Words: {0}": "字數：{0}",
        "{0} words": "{0} 個字",
        "File": "文件",
        "Edit": "編輯",
        "Insert": "插入",
        "View": "查看",
        "Format": "格式",
        "Table": "表格",
        "Tools": "工具",
        "Powered by {0}": "Powered by {0}",
        "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "在編輯區按ALT+F9打開菜單，按ALT+F10打開工具欄，按ALT+0查看幫助",
        "Image title": "圖片標題",
        "Border width": "邊框寬度",
        "Border style": "邊框樣式",
        "Error": "錯誤",
        "Warn": "警告",
        "Valid": "有效",
        "To open the popup, press Shift+Enter": "此快捷為軟回車（插入<br>）",
        "Rich Text Area. Press ALT-0 for help.": "編輯區. 按Alt+0鍵打開幫助",
        "System Font": "默認字體",
        "Failed to upload image: {0}": "圖片上傳失敗: {0}",
        "Failed to load plugin: {0} from url {1}": "插件加載失敗: {0} - {1}",
        "Failed to load plugin url: {0}": "插件加載失敗: {0}",
        "Failed to initialize plugin: {0}": "插件初始化失敗: {0}",
        "example": "示例",
        "Search": "查找",
        "All": "全部",
        "Currency": "貨幣",
        "Text": "文本",
        "Quotations": "引用",
        "Mathematical": "數學運算符",
        "Extended Latin": "拉丁語擴充",
        "Symbols": "符號",
        "Arrows": "箭頭",
        "User Defined": "自定義",
        "dollar sign": "美元",
        "currency sign": "貨幣",
        "euro-currency sign": "歐元",
        "colon sign": "冒號",
        "cruzeiro sign": "克魯賽羅幣",
        "french franc sign": "法郎",
        "lira sign": "裏拉",
        "mill sign": "密爾",
        "naira sign": "奈拉",
        "peseta sign": "比塞塔",
        "rupee sign": "盧比",
        "won sign": "韓元",
        "new sheqel sign": "新謝克爾",
        "dong sign": "越南盾",
        "kip sign": "老撾基普",
        "tugrik sign": "圖格裏克",
        "drachma sign": "德拉克馬",
        "german penny symbol": "德國便士",
        "peso sign": "比索",
        "guarani sign": "瓜拉尼",
        "austral sign": "澳元",
        "hryvnia sign": "格裏夫尼亞",
        "cedi sign": "塞地",
        "livre tournois sign": "裏弗弗爾",
        "spesmilo sign": "壹千spesoj的貨幣符號，該貨幣未使用",
        "tenge sign": "堅戈",
        "indian rupee sign": "印度盧比",
        "turkish lira sign": "土耳其裏拉",
        "nordic mark sign": "北歐馬克",
        "manat sign": "馬納特",
        "ruble sign": "盧布",
        "yen character": "日元",
        "yuan character": "人民幣元",
        "yuan character, in hong kong and taiwan": "元的繁體字",
        "yen/yuan character variant one": "元（大寫）",
        "Loading emoticons...": "正在加載表情文字...",
        "Could not load emoticons": "不能加載表情文字",
        "People": "人類",
        "Animals and Nature": "動物和自然",
        "Food and Drink": "食物和飲品",
        "Activity": "活動",
        "Travel and Places": "旅遊和地點",
        "Objects": "物件",
        "Flags": "旗幟",
        "Characters": "字數",
        "Characters (no spaces)": "字數（不含空格）",
        "Error: Form submit field collision.": "錯誤: 表單提交字段沖突.",
        "Error: No form element found.": "錯誤: 未找到可用的form.",
        "Update": "更新",
        "Color swatch": "顏色樣本",
        "Turquoise": "青綠",
        "Green": "綠色",
        "Blue": "藍色",
        "Purple": "紫色",
        "Navy Blue": "海軍藍",
        "Dark Turquoise": "深藍綠色",
        "Dark Green": "暗綠",
        "Medium Blue": "中藍",
        "Medium Purple": "中紫",
        "Midnight Blue": "深藍",
        "Yellow": "黃色",
        "Orange": "橙色",
        "Red": "紅色",
        "Light Gray": "淺灰",
        "Gray": "灰色",
        "Dark Yellow": "暗黃",
        "Dark Orange": "暗橙",
        "Dark Red": "暗紅",
        "Medium Gray": "中灰",
        "Dark Gray": "深灰",
        "Black": "黑色",
        "White": "白色",
        "Switch to or from fullscreen mode": "切換全屏模式",
        "Open help dialog": "打開幫助對話框",
        "history": "歷史",
        "styles": "樣式",
        "formatting": "格式化",
        "alignment": "對齊",
        "indentation": "縮進",
        "permanent pen": "記號筆",
        "comments": "註釋",
        "Anchor": "錨點",
        "Special character": "特殊字符",
        "Code sample": "代碼示例",
        "Color": "顏色",
        "Emoticons": "表情",
        "Document properties": "文檔屬性",
        "Image": "圖片",
        "Insert link": "插入鏈接",
        "Target": "目標",
        "Link": "鏈接",
        "Poster": "封面",
        "Media": "音視頻",
        "Print": "打印",
        "Prev": "上壹個",
        "Find and replace": "查找並替換",
        "Whole words": "全字匹配",
        "Spellcheck": "拼寫檢查",
        "Caption": "標題",
        "Insert template": "插入模板",
        //以下為補充漢化內容 
        "Code view": "代碼區域",
        "Select...": "選擇...",
        "Format Painter": "格式刷",
        "No templates defined.": "無內置模板",
        "Special character...": "特殊字符...",
        "Open link": "打開鏈接",
        "None": "無",
        "Count": "統計",
        "Document": "整個文檔",
        "Selection": "選取部分",
        "Words": "字詞數",
        "{0} characters": "{0} 個字符",
        "Alternative source URL": "替代資源地址",
        "Alternative description": "替代說明文字",
        "Accessibility": "可訪問性",
        "Image is decorative": "僅用於裝飾",
        "Line height": "行高",
        "Cut column": "剪切列",
        "Copy column": "復制列",
        "Paste column before": "粘貼到前方",
        "Paste column after": "粘貼到後方",
        "Copy column": "復制列",
        "Version": "版本",
        "Keyboard Navigation": "鍵盤導航",
        "Open popup menu for split buttons": "該組合鍵的作用是軟回車（插入br）",
    });

    //簡中
    tinymce.addI18n('zh_CN',{
        "Redo": "恢复",
        "Undo": "撤销",
        "Cut": "剪切",
        "Copy": "复制",
        "Paste": "粘贴",
        "Select all": "全选",
        "New document": "新建文档",
        "Ok": "确定",
        "Cancel": "取消",
        "Visual aids": "网格线",
        "Bold": "粗体",
        "Italic": "斜体",
        "Underline": "下划线",
        "Strikethrough": "删除线",
        "Superscript": "上标",
        "Subscript": "下标",
        "Clear formatting": "清除格式",
        "Align left": "左对齐",
        "Align center": "居中",
        "Align right": "右对齐",
        "Justify": "两端对齐",
        "Bullet list": "符号列表",
        "Numbered list": "数字列表",
        "Decrease indent": "减少缩进",
        "Increase indent": "增加缩进",
        "Close": "关闭",
        "Formats": "格式",
        "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.": "当前浏览器不支持访问剪贴板，请使用快捷键Ctrl+X/C/V复制粘贴",
        "Headers": "标题",
        "Header 1": "标题1",
        "Header 2": "标题2",
        "Header 3": "标题3",
        "Header 4": "标题4",
        "Header 5": "标题5",
        "Header 6": "标题6",
        "Headings": "标题",
        "Heading 1": "标题1",
        "Heading 2": "标题2",
        "Heading 3": "标题3",
        "Heading 4": "标题4",
        "Heading 5": "标题5",
        "Heading 6": "标题6",
        "Preformatted": "预格式化",
        "Div": "Div区块",
        "Pre": "预格式文本",
        "Code": "代码",
        "Paragraph": "段落",
        "Blockquote": "引用",
        "Inline": "文本",
        "Blocks": "区块",
        "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "当前为纯文本粘贴模式，再次点击可以回到普通粘贴模式。",
        "Fonts": "字体",
        "Font Sizes": "字号",
        "Class": "Class",
        "Browse for an image": "浏览图像",
        "OR": "或",
        "Drop an image here": "拖放一张图片文件至此",
        "Upload": "上传",
        "Block": "块",
        "Align": "对齐",
        "Default": "默认",
        "Circle": "空心圆",
        "Disc": "实心圆",
        "Square": "方块",
        "Lower Alpha": "小写英文字母",
        "Lower Greek": "小写希腊字母",
        "Lower Roman": "小写罗马字母",
        "Upper Alpha": "大写英文字母",
        "Upper Roman": "大写罗马字母",
        "Anchor...": "锚点...",
        "Name": "名称",
        "Id": "id",
        "Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "id应该以字母开头，后跟字母、数字、横线、点、冒号或下划线。",
        "You have unsaved changes are you sure you want to navigate away?": "你对文档的修改尚未保存，确定离开吗？",
        "Restore last draft": "恢复上次的草稿",
        "Special characters...": "特殊字符...",
        "Source code": "HTML源码",
        "Insert/Edit code sample": "插入/编辑代码示例",
        "Language": "语言",
        "Code sample...": "代码示例...",
        "Color Picker": "选取颜色",
        "R": "R",
        "G": "G",
        "B": "B",
        "Left to right": "从左到右",
        "Right to left": "从右到左",
        "Emoticons...": "表情符号...",
        "Metadata and Document Properties": "元数据和文档属性",
        "Title": "标题",
        "Keywords": "关键词",
        "Description": "描述",
        "Robots": "机器人",
        "Author": "作者",
        "Encoding": "编码",
        "Fullscreen": "全屏",
        "Action": "操作",
        "Shortcut": "快捷键",
        "Help": "帮助",
        "Address": "地址",
        "Focus to menubar": "移动焦点到菜单栏",
        "Focus to toolbar": "移动焦点到工具栏",
        "Focus to element path": "移动焦点到元素路径",
        "Focus to contextual toolbar": "移动焦点到上下文菜单",
        "Insert link (if link plugin activated)": "插入链接 (如果链接插件已激活)",
        "Save (if save plugin activated)": "保存(如果保存插件已激活)",
        "Find (if searchreplace plugin activated)": "查找(如果查找替换插件已激活)",
        "Plugins installed ({0}):": "已安装插件 ({0})：",
        "Premium plugins:": "优秀插件：",
        "Learn more...": "了解更多...",
        "You are using {0}": "你正在使用 {0}",
        "Plugins": "插件",
        "Handy Shortcuts": "快捷键",
        "Horizontal line": "水平分割线",
        "Insert/edit image": "插入/编辑图片",
        "Image description": "图片描述",
        "Source": "地址",
        "Dimensions": "大小",
        "Constrain proportions": "保持宽高比",
        "General": "常规",
        "Advanced": "高级",
        "Style": "样式",
        "Vertical space": "垂直边距",
        "Horizontal space": "水平边距",
        "Border": "边框",
        "Insert image": "插入图片",
        "Image...": "图片...",
        "Image list": "图片列表",
        "Rotate counterclockwise": "逆时针旋转",
        "Rotate clockwise": "顺时针旋转",
        "Flip vertically": "垂直翻转",
        "Flip horizontally": "水平翻转",
        "Edit image": "编辑图片",
        "Image options": "图片选项",
        "Zoom in": "放大",
        "Zoom out": "缩小",
        "Crop": "裁剪",
        "Resize": "调整大小",
        "Orientation": "方向",
        "Brightness": "亮度",
        "Sharpen": "锐化",
        "Contrast": "对比度",
        "Color levels": "色阶",
        "Gamma": "伽马值",
        "Invert": "反转",
        "Apply": "应用",
        "Back": "后退",
        "Insert date/time": "插入日期/时间",
        "Date/time": "日期/时间",
        "Insert/Edit Link": "插入/编辑链接",
        "Insert/edit link": "插入/编辑链接",
        "Text to display": "显示文字",
        "Url": "地址",
        "Open link in...": "链接打开方式...",
        "Current window": "当前窗口打开",
        "None": "在当前窗口/框架打开",
        "New window": "在新窗口打开",
        "Remove link": "删除链接",
        "Anchors": "锚点",
        "Link...": "链接...",
        "Paste or type a link": "粘贴或输入链接",
        "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "你所填写的URL地址为邮件地址，需要加上mailto:前缀吗？",
        "The URL you entered seems to be an external link. Do you want to add the required http:// prefix?": "你所填写的URL地址属于外部链接，需要加上http://:前缀吗？",
        "Link list": "链接列表",
        "Insert video": "插入视频",
        "Insert/edit video": "插入/编辑视频",
        "Insert/edit media": "插入/编辑媒体",
        "Alternative source": "替代资源",
        "Alternative image URL": "资源备用地址",
        "Media poster (Image URL)": "封面(图片地址)",
        "Paste your embed code below:": "将内嵌代码粘贴在下面:",
        "Embed": "内嵌",
        "Media...": "多媒体...",
        "Nonbreaking space": "不间断空格",
        "Page break": "分页符",
        "Paste as text": "粘贴为文本",
        "Preview": "预览",
        "Print...": "打印...",
        "Save": "保存",
        "Find": "查找",
        "Replace with": "替换为",
        "Replace": "替换",
        "Replace all": "替换全部",
        "Previous": "上一个",
        "Next": "下一个",
        "Find and replace...": "查找并替换...",
        "Could not find the specified string.": "未找到搜索内容。",
        "Match case": "区分大小写",
        "Find whole words only": "全单词匹配",
        "Spell check": "拼写检查",
        "Ignore": "忽略",
        "Ignore all": "忽略全部",
        "Finish": "完成",
        "Add to Dictionary": "添加到字典",
        "Insert table": "插入表格",
        "Table properties": "表格属性",
        "Delete table": "删除表格",
        "Cell": "单元格",
        "Row": "行",
        "Column": "列",
        "Cell properties": "单元格属性",
        "Merge cells": "合并单元格",
        "Split cell": "拆分单元格",
        "Insert row before": "在上方插入",
        "Insert row after": "在下方插入",
        "Delete row": "删除行",
        "Row properties": "行属性",
        "Cut row": "剪切行",
        "Copy row": "复制行",
        "Paste row before": "粘贴到上方",
        "Paste row after": "粘贴到下方",
        "Insert column before": "在左侧插入",
        "Insert column after": "在右侧插入",
        "Delete column": "删除列",
        "Cols": "列",
        "Rows": "行",
        "Width": "宽",
        "Height": "高",
        "Cell spacing": "单元格外间距",
        "Cell padding": "单元格内边距",
        "Show caption": "显示标题",
        "Left": "左对齐",
        "Center": "居中",
        "Right": "右对齐",
        "Cell type": "单元格类型",
        "Scope": "范围",
        "Alignment": "对齐方式",
        "H Align": "水平对齐",
        "V Align": "垂直对齐",
        "Top": "顶部对齐",
        "Middle": "垂直居中",
        "Bottom": "底部对齐",
        "Header cell": "表头单元格",
        "Row group": "行组",
        "Column group": "列组",
        "Row type": "行类型",
        "Header": "表头",
        "Body": "表体",
        "Footer": "表尾",
        "Border color": "边框颜色",
        "Insert template...": "插入模板...",
        "Templates": "模板",
        "Template": "模板",
        "Text color": "文字颜色",
        "Background color": "背景色",
        "Custom...": "自定义...",
        "Custom color": "自定义颜色",
        "No color": "无",
        "Remove color": "删除颜色",
        "Table of Contents": "目录",
        "Show blocks": "显示区块边框",
        "Show invisible characters": "显示不可见字符",
        "Word count": "字数统计",
        "Words: {0}": "字数：{0}",
        "{0} words": "{0} 个字",
        "File": "文件",
        "Edit": "编辑",
        "Insert": "插入",
        "View": "查看",
        "Format": "格式",
        "Table": "表格",
        "Tools": "工具",
        "Powered by {0}": "Powered by {0}",
        "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "在编辑区按ALT+F9打开菜单，按ALT+F10打开工具栏，按ALT+0查看帮助",
        "Image title": "图片标题",
        "Border width": "边框宽度",
        "Border style": "边框样式",
        "Error": "错误",
        "Warn": "警告",
        "Valid": "有效",
        "To open the popup, press Shift+Enter": "此快捷为软回车（插入<br>）",
        "Rich Text Area. Press ALT-0 for help.": "编辑区. 按Alt+0键打开帮助",
        "System Font": "默认字体",
        "Failed to upload image: {0}": "图片上传失败: {0}",
        "Failed to load plugin: {0} from url {1}": "插件加载失败: {0} - {1}",
        "Failed to load plugin url: {0}": "插件加载失败: {0}",
        "Failed to initialize plugin: {0}": "插件初始化失败: {0}",
        "example": "示例",
        "Search": "查找",
        "All": "全部",
        "Currency": "货币",
        "Text": "文本",
        "Quotations": "引用",
        "Mathematical": "数学运算符",
        "Extended Latin": "拉丁语扩充",
        "Symbols": "符号",
        "Arrows": "箭头",
        "User Defined": "自定义",
        "dollar sign": "美元",
        "currency sign": "货币",
        "euro-currency sign": "欧元",
        "colon sign": "冒号",
        "cruzeiro sign": "克鲁赛罗币",
        "french franc sign": "法郎",
        "lira sign": "里拉",
        "mill sign": "密尔",
        "naira sign": "奈拉",
        "peseta sign": "比塞塔",
        "rupee sign": "卢比",
        "won sign": "韩元",
        "new sheqel sign": "新谢克尔",
        "dong sign": "越南盾",
        "kip sign": "老挝基普",
        "tugrik sign": "图格里克",
        "drachma sign": "德拉克马",
        "german penny symbol": "德国便士",
        "peso sign": "比索",
        "guarani sign": "瓜拉尼",
        "austral sign": "澳元",
        "hryvnia sign": "格里夫尼亚",
        "cedi sign": "塞地",
        "livre tournois sign": "里弗弗尔",
        "spesmilo sign": "一千spesoj的货币符号，该货币未使用",
        "tenge sign": "坚戈",
        "indian rupee sign": "印度卢比",
        "turkish lira sign": "土耳其里拉",
        "nordic mark sign": "北欧马克",
        "manat sign": "马纳特",
        "ruble sign": "卢布",
        "yen character": "日元",
        "yuan character": "人民币元",
        "yuan character, in hong kong and taiwan": "元的繁体字",
        "yen/yuan character variant one": "元（大写）",
        "Loading emoticons...": "正在加载表情文字...",
        "Could not load emoticons": "不能加载表情文字",
        "People": "人类",
        "Animals and Nature": "动物和自然",
        "Food and Drink": "食物和饮品",
        "Activity": "活动",
        "Travel and Places": "旅游和地点",
        "Objects": "物件",
        "Flags": "旗帜",
        "Characters": "字数",
        "Characters (no spaces)": "字数（不含空格）",
        "Error: Form submit field collision.": "错误: 表单提交字段冲突.",
        "Error: No form element found.": "错误: 未找到可用的form.",
        "Update": "更新",
        "Color swatch": "颜色样本",
        "Turquoise": "青绿",
        "Green": "绿色",
        "Blue": "蓝色",
        "Purple": "紫色",
        "Navy Blue": "海军蓝",
        "Dark Turquoise": "深蓝绿色",
        "Dark Green": "暗绿",
        "Medium Blue": "中蓝",
        "Medium Purple": "中紫",
        "Midnight Blue": "深蓝",
        "Yellow": "黄色",
        "Orange": "橙色",
        "Red": "红色",
        "Light Gray": "浅灰",
        "Gray": "灰色",
        "Dark Yellow": "暗黄",
        "Dark Orange": "暗橙",
        "Dark Red": "暗红",
        "Medium Gray": "中灰",
        "Dark Gray": "深灰",
        "Black": "黑色",
        "White": "白色",
        "Switch to or from fullscreen mode": "切换全屏模式",
        "Open help dialog": "打开帮助对话框",
        "history": "历史",
        "styles": "样式",
        "formatting": "格式化",
        "alignment": "对齐",
        "indentation": "缩进",
        "permanent pen": "记号笔",
        "comments": "注释",
        "Anchor": "锚点",
        "Special character": "特殊字符",
        "Code sample": "代码示例",
        "Color": "颜色",
        "Emoticons": "表情",
        "Document properties": "文档属性",
        "Image": "图片",
        "Insert link": "插入链接",
        "Target": "目标",
        "Link": "链接",
        "Poster": "封面",
        "Media": "音视频",
        "Print": "打印",
        "Prev": "上一个",
        "Find and replace": "查找并替换",
        "Whole words": "全字匹配",
        "Spellcheck": "拼写检查",
        "Caption": "标题",
        "Insert template": "插入模板",
        //以下为补充汉化内容 
        "Code view": "代码区域",
        "Select...": "选择...",
        "Format Painter": "格式刷",
        "No templates defined.": "无内置模板",
        "Special character...": "特殊字符...",
        "Open link": "打开链接",
        "None": "无",
        "Count": "统计",
        "Document": "整个文档",
        "Selection": "选取部分",
        "Words": "字词数",
        "{0} characters": "{0} 个字符",
        "Alternative source URL": "替代资源地址",
        "Alternative description": "替代说明文字",
        "Accessibility": "可访问性",
        "Image is decorative": "仅用于装饰",
        "Line height": "行高",
        "Cut column": "剪切列",
        "Copy column": "复制列",
        "Paste column before": "粘贴到前方",
        "Paste column after": "粘贴到后方",
        "Copy column": "复制列",
        "Version": "版本",
        "Keyboard Navigation": "键盘导航",
        "Open popup menu for split buttons": "该组合键的作用是软回车（插入br）",
    });
</script>
<style>
    .tox.tox-tinymce.tox-tinymce--toolbar-sticky-on {
        z-index: 999;
    }

    button.tox-mbtn.tox-mbtn--select {
        width: 35px !important;
        white-space: nowrap;
    }
</style>

@push('head_js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/6.7.0/tinymce.min.js"></script>
@endpush